name: doormer
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  uuid: ^3.0.7
  

  flutter_bloc:
  dio:
  get_it:
  font_awesome_flutter:
  flutter_screenutil:
  equatable:
  logger: ^1.3.0
  go_router:
  flutter_secure_storage:
  test: ^1.25.7
  bloc_test: ^9.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  mockito: ^5.4.0
  build_runner: ^2.4.0

flutter:
  uses-material-design: true

  fonts:
    - family: Helvetica
      fonts:
        - asset: assets/fonts/Helvetica.ttf

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - lib/src/features/chat/data/repositories/file/dummydata.json
