// Mocks generated by Mockito 5.4.5 from annotations
// in doormer/test/src/features/chat/presentation/bloc/chat_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:doormer/src/features/chat/domain/entities/contact_entity.dart'
    as _i3;
import 'package:doormer/src/features/chat/domain/repositories/contact_repository.dart'
    as _i2;
import 'package:doormer/src/features/chat/domain/usecases/archive_chat_usecases.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeContactRepository_0 extends _i1.SmartFake
    implements _i2.ContactRepository {
  _FakeContactRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeContact_1 extends _i1.SmartFake implements _i3.Contact {
  _FakeContact_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GetSortedActiveChatList].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetSortedActiveChatList extends _i1.Mock
    implements _i4.GetSortedActiveChatList {
  MockGetSortedActiveChatList() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ContactRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeContactRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.ContactRepository);

  @override
  _i5.Future<List<_i3.Contact>> call() => (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue: _i5.Future<List<_i3.Contact>>.value(<_i3.Contact>[]),
      ) as _i5.Future<List<_i3.Contact>>);
}

/// A class which mocks [GetSortedArchivedChatList].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetSortedArchivedChatList extends _i1.Mock
    implements _i4.GetSortedArchivedChatList {
  MockGetSortedArchivedChatList() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ContactRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeContactRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.ContactRepository);

  @override
  _i5.Future<List<_i3.Contact>> call() => (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue: _i5.Future<List<_i3.Contact>>.value(<_i3.Contact>[]),
      ) as _i5.Future<List<_i3.Contact>>);
}

/// A class which mocks [DeleteChat].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeleteChat extends _i1.Mock implements _i4.DeleteChat {
  MockDeleteChat() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ContactRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeContactRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.ContactRepository);

  @override
  _i5.Future<void> call(String? chatId) => (super.noSuchMethod(
        Invocation.method(
          #call,
          [chatId],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}

/// A class which mocks [ToggleChatArchivedStatus].
///
/// See the documentation for Mockito's code generation for more information.
class MockToggleChatArchivedStatus extends _i1.Mock
    implements _i4.ToggleChatArchivedStatus {
  MockToggleChatArchivedStatus() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ContactRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeContactRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.ContactRepository);

  @override
  _i5.Future<_i3.Contact> call(_i3.Contact? contact) => (super.noSuchMethod(
        Invocation.method(
          #call,
          [contact],
        ),
        returnValue: _i5.Future<_i3.Contact>.value(_FakeContact_1(
          this,
          Invocation.method(
            #call,
            [contact],
          ),
        )),
      ) as _i5.Future<_i3.Contact>);
}
//push test
