// Mocks generated by Mockito 5.4.4 from annotations
// in doormer/test/src/features/chat/domain/usecases/archieve_chat_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:doormer/src/features/chat/domain/entities/chat_entity.dart'
    as _i4;
import 'package:doormer/src/features/chat/domain/repositories/chat_repository.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [ChatRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockChatRepository extends _i1.Mock implements _i2.ChatRepository {
  MockChatRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.Chat>> getChatList() => (super.noSuchMethod(
        Invocation.method(
          #getChatList,
          [],
        ),
        returnValue: _i3.Future<List<_i4.Chat>>.value(<_i4.Chat>[]),
      ) as _i3.Future<List<_i4.Chat>>);

  @override
  _i3.Future<void> toggleChat(String? chatId) => (super.noSuchMethod(
        Invocation.method(
          #archiveChat,
          [chatId],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> deleteChat(String? chatId) => (super.noSuchMethod(
        Invocation.method(
          #deleteChat,
          [chatId],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<List<_i4.Chat>> getArchivedList() => (super.noSuchMethod(
        Invocation.method(
          #getArchivedList,
          [],
        ),
        returnValue: _i3.Future<List<_i4.Chat>>.value(<_i4.Chat>[]),
      ) as _i3.Future<List<_i4.Chat>>);
}
